# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: car_proto/car.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63\x61r_proto/car.proto\x12\x03\x63\x61r\x1a\x1bgoogle/protobuf/empty.proto\"E\n\x03\x43\x61r\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05\x62rand\x18\x02 \x01(\t\x12\x14\n\x0crelease_year\x18\x03 \x01(\t\x12\r\n\x05\x63olor\x18\x04 \x01(\t\"\x10\n\x0e\x43\x61rListRequest\" \n\x12\x43\x61rRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xda\x01\n\rCarController\x12)\n\x04List\x12\x13.car.CarListRequest\x1a\x08.car.Car\"\x00\x30\x01\x12\x1e\n\x06\x43reate\x12\x08.car.Car\x1a\x08.car.Car\"\x00\x12/\n\x08Retrieve\x12\x17.car.CarRetrieveRequest\x1a\x08.car.Car\"\x00\x12\x1e\n\x06Update\x12\x08.car.Car\x1a\x08.car.Car\"\x00\x12-\n\x07\x44\x65stroy\x12\x08.car.Car\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')



_CAR = DESCRIPTOR.message_types_by_name['Car']
_CARLISTREQUEST = DESCRIPTOR.message_types_by_name['CarListRequest']
_CARRETRIEVEREQUEST = DESCRIPTOR.message_types_by_name['CarRetrieveRequest']
Car = _reflection.GeneratedProtocolMessageType('Car', (_message.Message,), {
  'DESCRIPTOR' : _CAR,
  '__module__' : 'car_proto.car_pb2'
  # @@protoc_insertion_point(class_scope:car.Car)
  })
_sym_db.RegisterMessage(Car)

CarListRequest = _reflection.GeneratedProtocolMessageType('CarListRequest', (_message.Message,), {
  'DESCRIPTOR' : _CARLISTREQUEST,
  '__module__' : 'car_proto.car_pb2'
  # @@protoc_insertion_point(class_scope:car.CarListRequest)
  })
_sym_db.RegisterMessage(CarListRequest)

CarRetrieveRequest = _reflection.GeneratedProtocolMessageType('CarRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _CARRETRIEVEREQUEST,
  '__module__' : 'car_proto.car_pb2'
  # @@protoc_insertion_point(class_scope:car.CarRetrieveRequest)
  })
_sym_db.RegisterMessage(CarRetrieveRequest)

_CARCONTROLLER = DESCRIPTOR.services_by_name['CarController']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CAR._serialized_start=57
  _CAR._serialized_end=126
  _CARLISTREQUEST._serialized_start=128
  _CARLISTREQUEST._serialized_end=144
  _CARRETRIEVEREQUEST._serialized_start=146
  _CARRETRIEVEREQUEST._serialized_end=178
  _CARCONTROLLER._serialized_start=181
  _CARCONTROLLER._serialized_end=399
# @@protoc_insertion_point(module_scope)
