# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from car_proto import car_pb2 as car__proto_dot_car__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class CarControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_stream(
                '/car.CarController/List',
                request_serializer=car__proto_dot_car__pb2.CarListRequest.SerializeToString,
                response_deserializer=car__proto_dot_car__pb2.Car.FromString,
                )
        self.Create = channel.unary_unary(
                '/car.CarController/Create',
                request_serializer=car__proto_dot_car__pb2.Car.SerializeToString,
                response_deserializer=car__proto_dot_car__pb2.Car.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/car.CarController/Retrieve',
                request_serializer=car__proto_dot_car__pb2.CarRetrieveRequest.SerializeToString,
                response_deserializer=car__proto_dot_car__pb2.Car.FromString,
                )
        self.Update = channel.unary_unary(
                '/car.CarController/Update',
                request_serializer=car__proto_dot_car__pb2.Car.SerializeToString,
                response_deserializer=car__proto_dot_car__pb2.Car.FromString,
                )
        self.Destroy = channel.unary_unary(
                '/car.CarController/Destroy',
                request_serializer=car__proto_dot_car__pb2.Car.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class CarControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CarControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_stream_rpc_method_handler(
                    servicer.List,
                    request_deserializer=car__proto_dot_car__pb2.CarListRequest.FromString,
                    response_serializer=car__proto_dot_car__pb2.Car.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=car__proto_dot_car__pb2.Car.FromString,
                    response_serializer=car__proto_dot_car__pb2.Car.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=car__proto_dot_car__pb2.CarRetrieveRequest.FromString,
                    response_serializer=car__proto_dot_car__pb2.Car.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=car__proto_dot_car__pb2.Car.FromString,
                    response_serializer=car__proto_dot_car__pb2.Car.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=car__proto_dot_car__pb2.Car.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'car.CarController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CarController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/car.CarController/List',
            car__proto_dot_car__pb2.CarListRequest.SerializeToString,
            car__proto_dot_car__pb2.Car.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/car.CarController/Create',
            car__proto_dot_car__pb2.Car.SerializeToString,
            car__proto_dot_car__pb2.Car.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/car.CarController/Retrieve',
            car__proto_dot_car__pb2.CarRetrieveRequest.SerializeToString,
            car__proto_dot_car__pb2.Car.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/car.CarController/Update',
            car__proto_dot_car__pb2.Car.SerializeToString,
            car__proto_dot_car__pb2.Car.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/car.CarController/Destroy',
            car__proto_dot_car__pb2.Car.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
