# Generated by Django 3.1.5 on 2022-03-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('realease_year', models.DateField()),
                ('color', models.CharField(default='black', max_length=6)),
            ],
            options={
                'ordering': ['brand'],
            },
        ),
    ]
