# Generated by Django 3.1.5 on 2022-03-06 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='realease_year',
            new_name='release_year',
        ),
    ]
